{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "ae307913",
   "metadata": {},
   "source": [
    "# Antinode Courier Beast Lab\n",
    "\n",
    "A Jupyter + Manim notebook for explaining the **Black Box Courier / Antinode Courier** RF game.\n",
    "\n",
    "This notebook explains the upgraded Courier game as a **playable RF-interference learning game**:\n",
    "\n",
    "- how the game loop works: **SCAN → TUNE → SAMPLE → DECODE**\n",
    "- how the game uses a simulated **spherical / multipath interference field**\n",
    "- why **ANTI** means constructive interference and **NULL** means destructive interference\n",
    "- how **FAST / MED / SLOW** filters teach Fourier/Laplace ideas as player skills\n",
    "- how lock score, ghost lanes, Wi-Fi/noise pressure, trace, and packet capture combine\n",
    "- Manim animation cells for teaching the concepts visually\n",
    "- interactive widgets for experimenting with levels, channels, filters, and phase\n",
    "\n",
    "> Safety / design boundary: this notebook models interference as a **game/simulation layer**. It is for your own console, own radios, and learning. It is not a guide to jam, disrupt, or interfere with other people's devices."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "440cbee5",
   "metadata": {},
   "source": [
    "## 0. Installation\n",
    "\n",
    "For normal simulation cells:\n",
    "\n",
    "```bash\n",
    "pip install numpy matplotlib pandas ipywidgets\n",
    "```\n",
    "\n",
    "For the animation cells:\n",
    "\n",
    "```bash\n",
    "pip install manim\n",
    "```\n",
    "\n",
    "In classic Jupyter / JupyterLab, widgets may need:\n",
    "\n",
    "```bash\n",
    "pip install jupyterlab_widgets\n",
    "```\n",
    "\n",
    "The Manim cells use the `%%manim` cell magic. In many notebook setups, you can run:\n",
    "\n",
    "```python\n",
    "%load_ext manim\n",
    "```\n",
    "\n",
    "If Manim is not installed, skip the Manim cells and still run the interactive game/simulation cells."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4849296f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Core imports used throughout the notebook\n",
    "import math\n",
    "import random\n",
    "from dataclasses import dataclass\n",
    "from typing import Dict, List, Tuple\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "try:\n",
    "    from IPython.display import display, clear_output, Markdown\n",
    "except Exception:\n",
    "    display = print\n",
    "    def clear_output(*args, **kwargs):\n",
    "        pass\n",
    "    Markdown = lambda x: x\n",
    "\n",
    "try:\n",
    "    import ipywidgets as widgets\n",
    "    WIDGETS_OK = True\n",
    "except Exception as e:\n",
    "    WIDGETS_OK = False\n",
    "    print(\"ipywidgets not available:\", e)\n",
    "\n",
    "plt.rcParams[\"figure.figsize\"] = (10, 4)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0e1d1b83",
   "metadata": {},
   "source": [
    "## 1. What game are we explaining?\n",
    "\n",
    "Your updated Courier game is now best described as:\n",
    "\n",
    "> **A hidden-signal courier puzzle where the player scans RF lanes, tunes a receiver, chooses a filter, and samples packets only when the interference field is favorable.**\n",
    "\n",
    "The firmware version we are explaining added these mechanics:\n",
    "\n",
    "| Mechanic | Game meaning | Learning meaning |\n",
    "|---|---|---|\n",
    "| `ANTI` | Capture window is strong | constructive interference / antinode |\n",
    "| `NULL` | Capture may fail even if RF looks strong | destructive interference / fade |\n",
    "| `RISE` / `FADE` | Wave quality is changing | phase drift over time |\n",
    "| Ghost lane | Fake strong RF peak | multipath / decoy source |\n",
    "| `FAST` filter | Tracks hopping/fast changes | wide/fast response filter |\n",
    "| `MED` filter | Balanced default | matched-filter idea |\n",
    "| `SLOW` filter | Stable in noise | smoothing / low-pass idea |\n",
    "| Trace | Sampling too loudly/often becomes risky | power discipline / stealth |\n",
    "\n",
    "The important design upgrade is that **interference is now a player skill**, not just random noise."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6b633b3f",
   "metadata": {},
   "source": [
    "## 2. The actual Courier loop\n",
    "\n",
    "The game loop is intentionally simple enough for a small OLED device:\n",
    "\n",
    "1. **SCAN**: inspect 8 RF bins/lane bars.\n",
    "2. **TUNE**: choose channel, rate, power, and filter.\n",
    "3. **SAMPLE**: press FIRE to open a costly receive/listen window.\n",
    "4. **DECODE**: once enough packet fragments are collected, solve/finish the box.\n",
    "\n",
    "A good player learns this mental model:\n",
    "\n",
    "```text\n",
    "Do not trust RF strength alone.\n",
    "Find the real lane, avoid ghost peaks, select the right filter,\n",
    "and sample during ANTI rather than NULL.\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "602f04b0",
   "metadata": {},
   "source": [
    "## 3. Level progression copied from the game design\n",
    "\n",
    "The game teaches one new idea at a time. This is why the first level is easier and later levels become more interference-focused."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e6733bbf",
   "metadata": {},
   "outputs": [],
   "source": [
    "levels = pd.DataFrame([\n",
    "    dict(level=1, base_channel=76, rate=\"1M\", symbols=3, clue=\"TUTORIAL\",   ghost=False, rate_matters=False, power_matters=False, hops=False, wifi=False, ble=False, twin=False, teaches=\"Basic scan/tune/sample loop\"),\n",
    "    dict(level=2, base_channel=43, rate=\"1M\", symbols=4, clue=\"ANTINODE\",   ghost=True,  rate_matters=False, power_matters=False, hops=False, wifi=False, ble=False, twin=False, teaches=\"Constructive interference timing\"),\n",
    "    dict(level=3, base_channel=91, rate=\"250K\", symbols=4, clue=\"RATE+WAVE\", ghost=True,  rate_matters=True,  power_matters=False, hops=False, wifi=False, ble=False, twin=False, teaches=\"Rate matching + wave quality\"),\n",
    "    dict(level=4, base_channel=24, rate=\"2M\", symbols=4, clue=\"PWR+NULL\",   ghost=True,  rate_matters=True,  power_matters=True,  hops=False, wifi=False, ble=False, twin=False, teaches=\"Power tradeoff + null fades\"),\n",
    "    dict(level=5, base_channel=64, rate=\"1M\", symbols=5, clue=\"FAST FILT\",  ghost=True,  rate_matters=True,  power_matters=True,  hops=True,  wifi=False, ble=False, twin=False, teaches=\"Hopping signal + FAST filter\"),\n",
    "    dict(level=6, base_channel=108,rate=\"250K\", symbols=5, clue=\"SLOW FILT\", ghost=True,  rate_matters=True,  power_matters=True,  hops=True,  wifi=True,  ble=False, twin=False, teaches=\"Noisy air + SLOW filter\"),\n",
    "    dict(level=7, base_channel=36, rate=\"2M\", symbols=5, clue=\"DECOY FFT\",  ghost=True,  rate_matters=True,  power_matters=True,  hops=True,  wifi=True,  ble=True,  twin=False, teaches=\"Noise/decoys + spectrum reading\"),\n",
    "    dict(level=8, base_channel=84, rate=\"1M\", symbols=5, clue=\"TWIN WAVE\",  ghost=True,  rate_matters=True,  power_matters=True,  hops=True,  wifi=True,  ble=True,  twin=True,  teaches=\"Twin beacon + multipath ghost logic\"),\n",
    "])\n",
    "levels"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1a084a19",
   "metadata": {},
   "source": [
    "## 4. RF bins: why the OLED map uses 8 lanes\n",
    "\n",
    "The nRF24 channel space is large enough that a tiny OLED cannot show every channel clearly. The game compresses channels into **8 bins**.\n",
    "\n",
    "That gives a simple visual map:\n",
    "\n",
    "```text\n",
    "BIN 0 | BIN 1 | BIN 2 | BIN 3 | BIN 4 | BIN 5 | BIN 6 | BIN 7\n",
    "```\n",
    "\n",
    "Each bin can show:\n",
    "\n",
    "- RF strength\n",
    "- Wi-Fi/noise pressure\n",
    "- BLE/decoy pressure\n",
    "- wave/interference quality\n",
    "- whether it is a ghost/null lane"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e17aa931",
   "metadata": {},
   "outputs": [],
   "source": [
    "BIN_COUNT = 8\n",
    "MAX_CHANNEL = 126\n",
    "\n",
    "RATE_NAMES = [\"250K\", \"1M\", \"2M\"]\n",
    "PWR_NAMES = [\"MIN\", \"LOW\", \"HI\", \"MAX\"]\n",
    "FILTER_NAMES = [\"FAST\", \"MED\", \"SLOW\"]\n",
    "TWO_PI = 2 * math.pi\n",
    "\n",
    "\n",
    "def channel_to_bin(channel: int) -> int:\n",
    "    \"\"\"Approximate the firmware's 0..125 channel -> 0..7 bin mapping.\"\"\"\n",
    "    channel = int(channel) % MAX_CHANNEL\n",
    "    return max(0, min(BIN_COUNT - 1, int(channel * BIN_COUNT / MAX_CHANNEL)))\n",
    "\n",
    "\n",
    "def bin_center_channel(bin_index: int) -> int:\n",
    "    return int((bin_index + 0.5) * MAX_CHANNEL / BIN_COUNT)\n",
    "\n",
    "[(b, bin_center_channel(b)) for b in range(BIN_COUNT)]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d040b20b",
   "metadata": {},
   "source": [
    "## 5. The interference field: spherical/multipath idea\n",
    "\n",
    "The firmware uses a compact wave model for game purposes:\n",
    "\n",
    "```text\n",
    "total field = direct beacon wave + reflected wave + optional decoy/twin wave\n",
    "score ≈ |total amplitude|\n",
    "```\n",
    "\n",
    "In real wave physics, a simple spherical wave can be written as:\n",
    "\n",
    "$$\n",
    "\\psi(r,t) = \\frac{A}{r}\\cos(kr - \\omega t + \\phi)\n",
    "$$\n",
    "\n",
    "When several waves meet, amplitudes add:\n",
    "\n",
    "$$\n",
    "\\psi_{total}=\\psi_1+\\psi_2+\\psi_3+\\cdots\n",
    "$$\n",
    "\n",
    "Then signal strength is related to squared magnitude:\n",
    "\n",
    "$$\n",
    "P \\propto |\\psi_{total}|^2\n",
    "$$\n",
    "\n",
    "The game simplifies this so it can run on ESP32 and fit an OLED display:\n",
    "\n",
    "- **high combined amplitude** → `ANTI`\n",
    "- **low combined amplitude** → `NULL`\n",
    "- changing amplitude over time → `RISE` / `FADE`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0f99cb10",
   "metadata": {},
   "outputs": [],
   "source": [
    "@dataclass\n",
    "class LevelFlags:\n",
    "    level: int\n",
    "    ghost: bool\n",
    "    rate_matters: bool\n",
    "    power_matters: bool\n",
    "    hops: bool\n",
    "    wifi: bool\n",
    "    ble: bool\n",
    "    twin: bool\n",
    "\n",
    "\n",
    "def flags_for_level(level: int) -> LevelFlags:\n",
    "    row = levels.iloc[level - 1]\n",
    "    return LevelFlags(\n",
    "        level=level,\n",
    "        ghost=bool(row.ghost),\n",
    "        rate_matters=bool(row.rate_matters),\n",
    "        power_matters=bool(row.power_matters),\n",
    "        hops=bool(row.hops),\n",
    "        wifi=bool(row.wifi),\n",
    "        ble=bool(row.ble),\n",
    "        twin=bool(row.twin),\n",
    "    )\n",
    "\n",
    "\n",
    "def interference_active(level: int) -> bool:\n",
    "    # Level 1 is tutorial. Wave field becomes a real skill from Level 2.\n",
    "    return level >= 2\n",
    "\n",
    "\n",
    "def interference_score_for_bin(bin_index: int, t: float, beacon_channel: int, decoy_channel: int, level: int) -> int:\n",
    "    \"\"\"\n",
    "    Python version of the game idea:\n",
    "    direct wave + reflected wave + optional decoy/twin wave.\n",
    "    t is a phase-like time value in radians.\n",
    "    \"\"\"\n",
    "    if not interference_active(level):\n",
    "        return 68\n",
    "    f = flags_for_level(level)\n",
    "    b = channel_to_bin(beacon_channel)\n",
    "    d = channel_to_bin(decoy_channel)\n",
    "    x = float(bin_index)\n",
    "    dx = x - float(b)\n",
    "    dd = x - float(d)\n",
    "\n",
    "    direct = math.cos(t + dx * 1.17) / (1.00 + 0.22 * abs(dx))\n",
    "    reflect = 0.64 * math.cos(t * 0.82 - dx * 1.63 + level * 0.37) / (1.25 + 0.14 * abs(dx + 2.0))\n",
    "\n",
    "    decoy = 0.0\n",
    "    if f.ghost or f.twin or f.ble:\n",
    "        decoy = 0.46 * math.cos(t * 1.31 + dd * 1.41 + 0.8) / (1.15 + 0.18 * abs(dd))\n",
    "\n",
    "    amp = abs(direct + reflect + decoy)\n",
    "    score = int(amp * 62.0 + 18.0)\n",
    "    if bin_index == channel_to_bin(beacon_channel):\n",
    "        score += 10\n",
    "    if bin_index == channel_to_bin(decoy_channel) and f.ghost:\n",
    "        score += 6\n",
    "    return int(np.clip(score, 0, 100))\n",
    "\n",
    "\n",
    "def field_word(score: int, level: int) -> str:\n",
    "    if not interference_active(level):\n",
    "        return \"TRAIN\"\n",
    "    if score < 30:\n",
    "        return \"NULL\"\n",
    "    if score >= 78:\n",
    "        return \"ANTI\"\n",
    "    if score >= 55:\n",
    "        return \"RISE\"\n",
    "    return \"FADE\"\n",
    "\n",
    "# Demo: one snapshot of the wave field for Level 8\n",
    "snapshot = [interference_score_for_bin(b, t=1.2, beacon_channel=84, decoy_channel=31, level=8) for b in range(BIN_COUNT)]\n",
    "[(b, s, field_word(s, 8)) for b, s in enumerate(snapshot)]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1e950df6",
   "metadata": {},
   "source": [
    "### Interactive: watch antinodes and nulls move\n",
    "\n",
    "Move the **phase** slider. Notice that the same channel can become `ANTI`, `RISE`, `FADE`, or `NULL` as the field changes.\n",
    "\n",
    "This is the core of the upgraded game: **timing matters**, not only channel selection."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b857c6e6",
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_interference_field(level=2, beacon_channel=43, decoy_channel=95, phase=0.0):\n",
    "    scores = [interference_score_for_bin(b, phase, beacon_channel, decoy_channel, level) for b in range(BIN_COUNT)]\n",
    "    labels = [field_word(s, level) for s in scores]\n",
    "\n",
    "    fig, ax = plt.subplots(figsize=(10, 4))\n",
    "    bars = ax.bar(range(BIN_COUNT), scores)\n",
    "    ax.set_ylim(0, 105)\n",
    "    ax.set_xlabel(\"RF bin / OLED lane\")\n",
    "    ax.set_ylabel(\"Interference field score\")\n",
    "    ax.set_title(f\"Level {level}: interference field snapshot\")\n",
    "    ax.axhline(78, linestyle=\"--\", linewidth=1, label=\"ANTI threshold\")\n",
    "    ax.axhline(30, linestyle=\"--\", linewidth=1, label=\"NULL threshold\")\n",
    "    ax.set_xticks(range(BIN_COUNT))\n",
    "\n",
    "    for i, (s, lab) in enumerate(zip(scores, labels)):\n",
    "        ax.text(i, s + 3, f\"{lab}\\n{s}\", ha=\"center\", va=\"bottom\", fontsize=9)\n",
    "\n",
    "    beacon_bin = channel_to_bin(beacon_channel)\n",
    "    decoy_bin = channel_to_bin(decoy_channel)\n",
    "    ax.text(beacon_bin, 102, \"BEACON\", ha=\"center\", fontsize=9)\n",
    "    if flags_for_level(level).ghost or flags_for_level(level).ble or flags_for_level(level).twin:\n",
    "        ax.text(decoy_bin, 94, \"GHOST\", ha=\"center\", fontsize=9)\n",
    "    ax.legend(loc=\"upper right\")\n",
    "    plt.show()\n",
    "\n",
    "if WIDGETS_OK:\n",
    "    display(widgets.interactive(\n",
    "        plot_interference_field,\n",
    "        level=widgets.IntSlider(value=2, min=1, max=8, step=1, description=\"Level\"),\n",
    "        beacon_channel=widgets.IntSlider(value=43, min=0, max=125, step=1, description=\"Beacon CH\"),\n",
    "        decoy_channel=widgets.IntSlider(value=95, min=0, max=125, step=1, description=\"Ghost CH\"),\n",
    "        phase=widgets.FloatSlider(value=0.0, min=0.0, max=float(2*np.pi), step=0.05, description=\"Phase\"),\n",
    "    ))\n",
    "else:\n",
    "    plot_interference_field()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a48bdba0",
   "metadata": {},
   "source": [
    "## 6. Why RF strength alone is not enough\n",
    "\n",
    "A naive game would say:\n",
    "\n",
    "```text\n",
    "strong bar = correct answer\n",
    "```\n",
    "\n",
    "But this game teaches a better RF lesson:\n",
    "\n",
    "```text\n",
    "strong bar can be real signal, ghost signal, Wi-Fi/noise pressure, or a bad multipath peak\n",
    "```\n",
    "\n",
    "A good player checks:\n",
    "\n",
    "1. Is the selected channel close to the hidden beacon?\n",
    "2. Is the field `ANTI` or at least `RISE`?\n",
    "3. Is it avoiding `NULL`?\n",
    "4. Is the filter appropriate?\n",
    "5. Is the rate/power correct for this level?\n",
    "6. Is the trace too high?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7e1ee82b",
   "metadata": {},
   "outputs": [],
   "source": [
    "def selected_interference_score(selected_channel: int, beacon_channel: int, decoy_channel: int, level: int, phase: float) -> int:\n",
    "    if not interference_active(level):\n",
    "        return 72\n",
    "    sel_bin = channel_to_bin(selected_channel)\n",
    "    dist = abs(selected_channel - beacon_channel)\n",
    "    dist = min(dist, MAX_CHANNEL - dist)\n",
    "    s = interference_score_for_bin(sel_bin, phase, beacon_channel, decoy_channel, level)\n",
    "\n",
    "    # Correct channel lets player exploit the antinode more sharply.\n",
    "    if dist == 0:\n",
    "        s += 10\n",
    "    elif dist <= 1:\n",
    "        s += 4\n",
    "    elif sel_bin != channel_to_bin(beacon_channel):\n",
    "        s -= 14\n",
    "\n",
    "    f = flags_for_level(level)\n",
    "    if f.ghost and sel_bin == channel_to_bin(decoy_channel):\n",
    "        s -= 22\n",
    "    if f.twin and sel_bin == channel_to_bin((beacon_channel + 31) % MAX_CHANNEL):\n",
    "        s -= 16\n",
    "    return int(np.clip(s, 0, 100))\n",
    "\n",
    "\n",
    "def selected_filter_score(level: int, selected_filter: int, selected_channel: int, beacon_channel: int, decoy_channel: int, phase: float, wifi_pressure=0, ble_pressure=0, ghost_here=False) -> int:\n",
    "    \"\"\"Python version of the FAST/MED/SLOW scoring idea.\"\"\"\n",
    "    f = flags_for_level(level)\n",
    "    noise = wifi_pressure + ble_pressure + (2 if ghost_here else 0)\n",
    "    s = 9\n",
    "    wave = selected_interference_score(selected_channel, beacon_channel, decoy_channel, level, phase)\n",
    "\n",
    "    if level <= 2:\n",
    "        s += 5 if selected_filter == 1 else 2\n",
    "    elif selected_filter == 0:  # FAST\n",
    "        s += 7 if f.hops else 1\n",
    "        if noise >= 4:\n",
    "            s -= 4\n",
    "        if wave >= 78:\n",
    "            s += 2\n",
    "    elif selected_filter == 1:  # MED\n",
    "        s += 4\n",
    "        if f.twin:\n",
    "            s -= 2\n",
    "    else:  # SLOW\n",
    "        s += 7 if (f.wifi or noise >= 4) else 1\n",
    "        if f.hops and wave < 60:\n",
    "            s -= 4\n",
    "\n",
    "    return int(np.clip(s, 0, 16))\n",
    "\n",
    "\n",
    "def compute_lock_score(\n",
    "    level:int,\n",
    "    selected_channel:int,\n",
    "    beacon_channel:int,\n",
    "    selected_rate:int,\n",
    "    beacon_rate:int,\n",
    "    selected_power:int,\n",
    "    power_need:int,\n",
    "    selected_filter:int,\n",
    "    phase:float,\n",
    "    decoy_channel:int,\n",
    "    trace:int=0,\n",
    "    wifi_pressure:int=0,\n",
    "    ble_pressure:int=0,\n",
    ") -> int:\n",
    "    \"\"\"Game-style lock score. This is not exact firmware, but follows the same design logic.\"\"\"\n",
    "    f = flags_for_level(level)\n",
    "    score = 0\n",
    "\n",
    "    dist = abs(selected_channel - beacon_channel)\n",
    "    dist = min(dist, MAX_CHANNEL - dist)\n",
    "    if dist == 0:\n",
    "        score += 40\n",
    "    elif dist <= 1:\n",
    "        score += 28\n",
    "    elif channel_to_bin(selected_channel) == channel_to_bin(beacon_channel):\n",
    "        score += 16\n",
    "\n",
    "    if (not f.rate_matters) or selected_rate == beacon_rate:\n",
    "        score += 22\n",
    "    else:\n",
    "        score += 8 if abs(selected_rate - beacon_rate) == 1 else 2\n",
    "\n",
    "    if not f.power_matters:\n",
    "        score += 14\n",
    "    else:\n",
    "        pd = abs(selected_power - power_need)\n",
    "        score += 16 if pd == 0 else (9 if pd == 1 else 3)\n",
    "\n",
    "    # Sample timing score: phase windows represent pulse timing.\n",
    "    pulse_phase = (phase % TWO_PI) / TWO_PI\n",
    "    score += 12 if pulse_phase < 0.25 or pulse_phase > 0.80 else 5\n",
    "\n",
    "    wave_score = selected_interference_score(selected_channel, beacon_channel, decoy_channel, level, phase)\n",
    "    ghost_here = channel_to_bin(selected_channel) == channel_to_bin(decoy_channel) and f.ghost\n",
    "    filt_score = selected_filter_score(level, selected_filter, selected_channel, beacon_channel, decoy_channel, phase, wifi_pressure, ble_pressure, ghost_here)\n",
    "\n",
    "    if not interference_active(level):\n",
    "        score += 8\n",
    "    elif wave_score >= 78:\n",
    "        score += 18\n",
    "    elif wave_score >= 55:\n",
    "        score += 9\n",
    "    elif wave_score < 28:\n",
    "        score -= 18\n",
    "    else:\n",
    "        score -= 5\n",
    "\n",
    "    score += filt_score - 8\n",
    "\n",
    "    if f.wifi and wifi_pressure >= 3:\n",
    "        score -= 8\n",
    "    if f.ble and ble_pressure >= 3 and channel_to_bin(selected_channel) != channel_to_bin(beacon_channel):\n",
    "        score -= 10\n",
    "    if ghost_here:\n",
    "        score -= 12\n",
    "\n",
    "    score -= trace * 3\n",
    "    return int(np.clip(score, 0, 100))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0285433f",
   "metadata": {},
   "source": [
    "### Interactive: tune the Courier lock\n",
    "\n",
    "Use the controls to see what creates a strong lock. The goal is not merely high RF. The strongest game state is usually:\n",
    "\n",
    "```text\n",
    "right channel + right rate/power + good filter + ANTI field + low trace\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6d38d7f5",
   "metadata": {},
   "outputs": [],
   "source": [
    "def visualize_lock(\n",
    "    level=5,\n",
    "    selected_channel=64,\n",
    "    beacon_channel=64,\n",
    "    decoy_channel=30,\n",
    "    selected_rate=1,\n",
    "    selected_power=1,\n",
    "    selected_filter=0,\n",
    "    trace=0,\n",
    "    wifi_pressure=0,\n",
    "    ble_pressure=0,\n",
    "    phase=0.0,\n",
    "):\n",
    "    row = levels.iloc[level-1]\n",
    "    beacon_rate = {\"250K\":0,\"1M\":1,\"2M\":2}[row.rate]\n",
    "    power_need = 1 + (level >= 4)\n",
    "\n",
    "    wave = selected_interference_score(selected_channel, beacon_channel, decoy_channel, level, phase)\n",
    "    filt = selected_filter_score(level, selected_filter, selected_channel, beacon_channel, decoy_channel, phase, wifi_pressure, ble_pressure)\n",
    "    lock = compute_lock_score(level, selected_channel, beacon_channel, selected_rate, beacon_rate, selected_power, power_need, selected_filter, phase, decoy_channel, trace, wifi_pressure, ble_pressure)\n",
    "    label = field_word(wave, level)\n",
    "\n",
    "    print(f\"Level {level} clue: {row.clue} — {row.teaches}\")\n",
    "    print(f\"Selected filter: {FILTER_NAMES[selected_filter]} | Selected rate: {RATE_NAMES[selected_rate]} | Selected power: {PWR_NAMES[selected_power]}\")\n",
    "    print(f\"Field: {label} ({wave}/100), Filter score: {filt}/16, Lock score: {lock}/100\")\n",
    "\n",
    "    names = [\"Wave\", \"Filter\", \"Lock\"]\n",
    "    values = [wave, filt/16*100, lock]\n",
    "    fig, ax = plt.subplots(figsize=(8,3))\n",
    "    ax.bar(names, values)\n",
    "    ax.set_ylim(0, 100)\n",
    "    ax.axhline(65, linestyle=\"--\", linewidth=1)\n",
    "    ax.axhline(86, linestyle=\"--\", linewidth=1)\n",
    "    ax.set_title(\"Courier capture readiness\")\n",
    "    for i, v in enumerate(values):\n",
    "        ax.text(i, v+3, f\"{v:.0f}\", ha=\"center\")\n",
    "    plt.show()\n",
    "\n",
    "if WIDGETS_OK:\n",
    "    display(widgets.interactive(\n",
    "        visualize_lock,\n",
    "        level=widgets.IntSlider(value=5, min=1, max=8, step=1, description=\"Level\"),\n",
    "        selected_channel=widgets.IntSlider(value=64, min=0, max=125, step=1, description=\"Your CH\"),\n",
    "        beacon_channel=widgets.IntSlider(value=64, min=0, max=125, step=1, description=\"Beacon\"),\n",
    "        decoy_channel=widgets.IntSlider(value=30, min=0, max=125, step=1, description=\"Ghost\"),\n",
    "        selected_rate=widgets.Dropdown(options=[(\"250K\",0),(\"1M\",1),(\"2M\",2)], value=1, description=\"Rate\"),\n",
    "        selected_power=widgets.Dropdown(options=[(\"MIN\",0),(\"LOW\",1),(\"HI\",2),(\"MAX\",3)], value=1, description=\"Power\"),\n",
    "        selected_filter=widgets.Dropdown(options=[(\"FAST\",0),(\"MED\",1),(\"SLOW\",2)], value=0, description=\"Filter\"),\n",
    "        trace=widgets.IntSlider(value=0, min=0, max=8, step=1, description=\"Trace\"),\n",
    "        wifi_pressure=widgets.IntSlider(value=0, min=0, max=3, step=1, description=\"WiFi\"),\n",
    "        ble_pressure=widgets.IntSlider(value=0, min=0, max=3, step=1, description=\"BLE\"),\n",
    "        phase=widgets.FloatSlider(value=0, min=0, max=float(2*np.pi), step=0.05, description=\"Phase\"),\n",
    "    ))\n",
    "else:\n",
    "    visualize_lock()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f4c5b17e",
   "metadata": {},
   "source": [
    "## 7. Filter mechanic: Fourier/Laplace without making the player do equations\n",
    "\n",
    "The player sees only:\n",
    "\n",
    "```text\n",
    "FILT FAST / MED / SLOW\n",
    "```\n",
    "\n",
    "But underneath, this is a very good educational metaphor:\n",
    "\n",
    "| Filter | Game behavior | Signal-processing idea |\n",
    "|---|---|---|\n",
    "| FAST | reacts quickly, good for hopping signals | broader bandwidth / faster time response |\n",
    "| MED | reliable default | matched-filter style compromise |\n",
    "| SLOW | stable in noisy levels | smoothing / low-pass response |\n",
    "\n",
    "Fourier intuition:\n",
    "\n",
    "- A fast-changing signal needs a filter that can follow changes.\n",
    "- A noisy environment benefits from narrower/smoother filtering.\n",
    "\n",
    "Laplace/control intuition:\n",
    "\n",
    "A simple first-order smoothing system can be modeled as:\n",
    "\n",
    "$$\n",
    "H(s)=\\frac{1}{\\tau s + 1}\n",
    "$$\n",
    "\n",
    "- small `tau` → fast but jittery\n",
    "- large `tau` → slow but stable"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b5efd9ff",
   "metadata": {},
   "outputs": [],
   "source": [
    "def make_signal(n=400, hopping=False, noise=0.3, seed=0):\n",
    "    rng = np.random.default_rng(seed)\n",
    "    t = np.linspace(0, 8, n)\n",
    "    freq = np.where(t < 4, 2.0, 4.5) if hopping else np.full_like(t, 2.0)\n",
    "    phase = np.cumsum(freq) * (t[1]-t[0]) * 2*np.pi\n",
    "    clean = np.sin(phase)\n",
    "    y = clean + rng.normal(0, noise, size=n)\n",
    "    return t, clean, y\n",
    "\n",
    "\n",
    "def exponential_smooth(y, alpha):\n",
    "    out = np.zeros_like(y)\n",
    "    out[0] = y[0]\n",
    "    for i in range(1, len(y)):\n",
    "        out[i] = alpha * y[i] + (1-alpha) * out[i-1]\n",
    "    return out\n",
    "\n",
    "\n",
    "def plot_filters(hopping=True, noise=0.5):\n",
    "    t, clean, y = make_signal(hopping=hopping, noise=noise, seed=2)\n",
    "    filters = {\n",
    "        \"FAST\": 0.45,\n",
    "        \"MED\": 0.20,\n",
    "        \"SLOW\": 0.06,\n",
    "    }\n",
    "    fig, ax = plt.subplots(figsize=(10,4))\n",
    "    ax.plot(t, y, linewidth=0.7, alpha=0.45, label=\"noisy observed signal\")\n",
    "    ax.plot(t, clean, linewidth=1.5, label=\"hidden clean signal\")\n",
    "    for name, alpha in filters.items():\n",
    "        ax.plot(t, exponential_smooth(y, alpha), linewidth=1.2, label=name)\n",
    "    ax.set_title(\"FAST/MED/SLOW as smoothing choices\")\n",
    "    ax.set_xlabel(\"time\")\n",
    "    ax.set_ylabel(\"amplitude\")\n",
    "    ax.legend()\n",
    "    plt.show()\n",
    "\n",
    "if WIDGETS_OK:\n",
    "    display(widgets.interactive(\n",
    "        plot_filters,\n",
    "        hopping=widgets.Checkbox(value=True, description=\"Hopping signal\"),\n",
    "        noise=widgets.FloatSlider(value=0.5, min=0.0, max=1.5, step=0.05, description=\"Noise\"),\n",
    "    ))\n",
    "else:\n",
    "    plot_filters()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c1eb3b36",
   "metadata": {},
   "source": [
    "## 8. Mini playable Courier simulator\n",
    "\n",
    "This is a tiny notebook version of the game logic. It is not the whole firmware, but it teaches the same skills:\n",
    "\n",
    "- choose a channel\n",
    "- choose a rate\n",
    "- choose a power\n",
    "- choose a filter\n",
    "- press sample when the field is good\n",
    "- avoid ghost/null states\n",
    "\n",
    "Try to capture all fragments with high score."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "58e82057",
   "metadata": {},
   "outputs": [],
   "source": [
    "class MiniCourier:\n",
    "    def __init__(self, level=5, seed=1):\n",
    "        self.rng = random.Random(seed)\n",
    "        self.level = level\n",
    "        row = levels.iloc[level-1]\n",
    "        self.beacon = int(row.base_channel)\n",
    "        self.decoy = (self.beacon + 47) % MAX_CHANNEL\n",
    "        self.beacon_rate = {\"250K\":0,\"1M\":1,\"2M\":2}[row.rate]\n",
    "        self.power_need = 1 + (level >= 4)\n",
    "        self.selected_channel = self.beacon\n",
    "        self.selected_rate = self.beacon_rate\n",
    "        self.selected_power = min(self.power_need, 3)\n",
    "        self.selected_filter = 0 if level == 5 else (2 if level >= 6 else 1)\n",
    "        self.phase = 0.0\n",
    "        self.trace = 0\n",
    "        self.battery = 100\n",
    "        self.score = 1000\n",
    "        self.fragments = 0\n",
    "        self.need = int(row.symbols)\n",
    "        self.last = \"Ready\"\n",
    "\n",
    "    def tick(self, dt=0.35):\n",
    "        self.phase = (self.phase + dt) % TWO_PI\n",
    "\n",
    "    def sample(self):\n",
    "        self.battery = max(0, self.battery - (3 if self.selected_power >= 2 else 2))\n",
    "        if self.selected_power >= 3:\n",
    "            self.trace = min(11, self.trace + 1)\n",
    "\n",
    "        lock = compute_lock_score(\n",
    "            self.level, self.selected_channel, self.beacon,\n",
    "            self.selected_rate, self.beacon_rate,\n",
    "            self.selected_power, self.power_need,\n",
    "            self.selected_filter, self.phase, self.decoy,\n",
    "            self.trace, wifi_pressure=3 if flags_for_level(self.level).wifi else 0,\n",
    "            ble_pressure=3 if flags_for_level(self.level).ble else 0,\n",
    "        )\n",
    "        wave = selected_interference_score(self.selected_channel, self.beacon, self.decoy, self.level, self.phase)\n",
    "        filt = selected_filter_score(self.level, self.selected_filter, self.selected_channel, self.beacon, self.decoy, self.phase)\n",
    "        ghost = flags_for_level(self.level).ghost and channel_to_bin(self.selected_channel) == channel_to_bin(self.decoy)\n",
    "\n",
    "        if ghost:\n",
    "            self.last = \"DECOY LANE\"\n",
    "            self.score -= 20\n",
    "            return False\n",
    "        if wave < 30:\n",
    "            self.last = \"NULL FADE — wait for ANTI\"\n",
    "            self.score -= 15\n",
    "            return False\n",
    "        if filt < 6:\n",
    "            self.last = \"BAD FILTER\"\n",
    "            self.score -= 15\n",
    "            return False\n",
    "\n",
    "        chance = np.clip(0.20 + lock/125 + (0.15 if wave >= 78 else 0.0), 0.05, 0.98)\n",
    "        if self.rng.random() < chance:\n",
    "            self.fragments += 1\n",
    "            bonus = 75 + (35 if wave >= 78 else 0) + (15 if filt >= 13 else 0)\n",
    "            self.score += bonus\n",
    "            self.last = \"ANTINODE HIT\" if wave >= 78 else \"FRAG FOUND\"\n",
    "            if flags_for_level(self.level).hops and self.fragments < self.need:\n",
    "                self.beacon = (self.beacon + self.rng.choice([13, 17, 23, 31])) % MAX_CHANNEL\n",
    "                self.decoy = (self.beacon + self.rng.choice([29, 47, 61])) % MAX_CHANNEL\n",
    "                self.last += \" — SIGNAL MOVED\"\n",
    "            return True\n",
    "        else:\n",
    "            self.last = \"PHASE LOST\" if lock >= 65 else \"WEAK LOCK\"\n",
    "            self.score -= 10\n",
    "            return False\n",
    "\n",
    "    def status(self):\n",
    "        wave = selected_interference_score(self.selected_channel, self.beacon, self.decoy, self.level, self.phase)\n",
    "        filt = selected_filter_score(self.level, self.selected_filter, self.selected_channel, self.beacon, self.decoy, self.phase)\n",
    "        lock = compute_lock_score(self.level, self.selected_channel, self.beacon, self.selected_rate, self.beacon_rate, self.selected_power, self.power_need, self.selected_filter, self.phase, self.decoy, self.trace)\n",
    "        return dict(level=self.level, beacon=self.beacon, ghost=self.decoy, ch=self.selected_channel, rate=RATE_NAMES[self.selected_rate], power=PWR_NAMES[self.selected_power], filter=FILTER_NAMES[self.selected_filter], field=field_word(wave, self.level), wave=wave, filt=filt, lock=lock, fragments=f\"{self.fragments}/{self.need}\", battery=self.battery, trace=self.trace, score=self.score, last=self.last)\n",
    "\n",
    "\n",
    "def show_mini_state(game):\n",
    "    st = game.status()\n",
    "    display(pd.DataFrame([st]))\n",
    "    scores = [interference_score_for_bin(b, game.phase, game.beacon, game.decoy, game.level) for b in range(BIN_COUNT)]\n",
    "    fig, ax = plt.subplots(figsize=(9,3))\n",
    "    ax.bar(range(BIN_COUNT), scores)\n",
    "    ax.set_ylim(0,105)\n",
    "    ax.set_title(\"Current RF/interference bins\")\n",
    "    ax.set_xlabel(\"bin\")\n",
    "    ax.set_ylabel(\"field\")\n",
    "    ax.axhline(78, linestyle=\"--\", linewidth=1)\n",
    "    ax.axhline(30, linestyle=\"--\", linewidth=1)\n",
    "    ax.text(channel_to_bin(game.beacon), 102, \"BEACON\", ha=\"center\")\n",
    "    ax.text(channel_to_bin(game.decoy), 92, \"GHOST\", ha=\"center\")\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "16c78cea",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Run this cell to play a small interactive notebook version.\n",
    "if WIDGETS_OK:\n",
    "    game = MiniCourier(level=5, seed=3)\n",
    "    out = widgets.Output()\n",
    "\n",
    "    level_dd = widgets.Dropdown(options=list(range(1,9)), value=5, description=\"Level\")\n",
    "    ch_slider = widgets.IntSlider(value=game.selected_channel, min=0, max=125, description=\"CH\")\n",
    "    rate_dd = widgets.Dropdown(options=[(\"250K\",0),(\"1M\",1),(\"2M\",2)], value=game.selected_rate, description=\"Rate\")\n",
    "    pwr_dd = widgets.Dropdown(options=[(\"MIN\",0),(\"LOW\",1),(\"HI\",2),(\"MAX\",3)], value=game.selected_power, description=\"Power\")\n",
    "    filt_dd = widgets.Dropdown(options=[(\"FAST\",0),(\"MED\",1),(\"SLOW\",2)], value=game.selected_filter, description=\"Filter\")\n",
    "    new_btn = widgets.Button(description=\"New game\")\n",
    "    tick_btn = widgets.Button(description=\"Wait / phase tick\")\n",
    "    sample_btn = widgets.Button(description=\"FIRE sample\", button_style=\"warning\")\n",
    "\n",
    "    def sync_to_game():\n",
    "        game.selected_channel = ch_slider.value\n",
    "        game.selected_rate = rate_dd.value\n",
    "        game.selected_power = pwr_dd.value\n",
    "        game.selected_filter = filt_dd.value\n",
    "\n",
    "    def redraw():\n",
    "        with out:\n",
    "            clear_output(wait=True)\n",
    "            show_mini_state(game)\n",
    "            if game.fragments >= game.need:\n",
    "                print(\"DECODE READY — box solved!\")\n",
    "            elif game.battery <= 0:\n",
    "                print(\"Battery empty — mission failed.\")\n",
    "\n",
    "    def on_new(_):\n",
    "        global game\n",
    "        game = MiniCourier(level=level_dd.value, seed=random.randint(0,9999))\n",
    "        ch_slider.value = game.selected_channel\n",
    "        rate_dd.value = game.selected_rate\n",
    "        pwr_dd.value = game.selected_power\n",
    "        filt_dd.value = game.selected_filter\n",
    "        redraw()\n",
    "\n",
    "    def on_tick(_):\n",
    "        sync_to_game()\n",
    "        game.tick()\n",
    "        redraw()\n",
    "\n",
    "    def on_sample(_):\n",
    "        sync_to_game()\n",
    "        game.sample()\n",
    "        game.tick(0.25)\n",
    "        redraw()\n",
    "\n",
    "    new_btn.on_click(on_new)\n",
    "    tick_btn.on_click(on_tick)\n",
    "    sample_btn.on_click(on_sample)\n",
    "\n",
    "    controls = widgets.VBox([\n",
    "        widgets.HBox([level_dd, new_btn, tick_btn, sample_btn]),\n",
    "        widgets.HBox([ch_slider, rate_dd, pwr_dd, filt_dd]),\n",
    "        out\n",
    "    ])\n",
    "    display(controls)\n",
    "    redraw()\n",
    "else:\n",
    "    game = MiniCourier(level=5)\n",
    "    show_mini_state(game)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "41e1c713",
   "metadata": {},
   "source": [
    "## 9. Manim setup\n",
    "\n",
    "The cells below are Manim animation cells. Run this once:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8c88ff7b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Uncomment and run if Manim is installed in your Jupyter environment.\n",
    "# %load_ext manim"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e77d1ea7",
   "metadata": {},
   "source": [
    "## 10. Manim Scene 1 — Spherical wave interference\n",
    "\n",
    "This animation shows two circular wave sources. Where rings reinforce, label it **ANTINODE**. Where they cancel, label it **NULL**.\n",
    "\n",
    "Run the next cell only after `%load_ext manim` works."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6dd3fd2f",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%manim -qm SphericalWaveInterference\n",
    "from manim import *\n",
    "import numpy as np\n",
    "\n",
    "class SphericalWaveInterference(Scene):\n",
    "    def construct(self):\n",
    "        title = Text(\"Interference Field: ANTI vs NULL\", font_size=34).to_edge(UP)\n",
    "        self.play(Write(title))\n",
    "\n",
    "        left = Dot(LEFT*2.2, radius=0.08)\n",
    "        right = Dot(RIGHT*2.2, radius=0.08)\n",
    "        left_label = Text(\"Beacon\", font_size=22).next_to(left, DOWN)\n",
    "        right_label = Text(\"Reflection / Ghost\", font_size=22).next_to(right, DOWN)\n",
    "        self.play(FadeIn(left), FadeIn(right), Write(left_label), Write(right_label))\n",
    "\n",
    "        waves = VGroup()\n",
    "        for src in [left.get_center(), right.get_center()]:\n",
    "            for r in np.linspace(0.5, 4.8, 8):\n",
    "                c = Circle(radius=r, stroke_width=2).move_to(src)\n",
    "                waves.add(c)\n",
    "        self.play(LaggedStart(*[Create(w) for w in waves], lag_ratio=0.04), run_time=2.0)\n",
    "\n",
    "        anti = Text(\"ANTI\\nconstructive\", font_size=28).move_to(UP*0.8)\n",
    "        null = Text(\"NULL\\ndestructive\", font_size=28).move_to(DOWN*1.6)\n",
    "        anti_box = SurroundingRectangle(anti, buff=0.2)\n",
    "        null_box = SurroundingRectangle(null, buff=0.2)\n",
    "        self.play(Write(anti), Create(anti_box), Write(null), Create(null_box))\n",
    "\n",
    "        equation = MathTex(r\"\\psi_{total}=\\psi_{direct}+\\psi_{reflected}+\\psi_{ghost}\").scale(0.7).to_edge(DOWN)\n",
    "        self.play(Write(equation))\n",
    "        self.wait(2)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6d843e70",
   "metadata": {},
   "source": [
    "## 11. Manim Scene 2 — Courier game loop\n",
    "\n",
    "This animation explains the actual player loop: scan the spectrum, tune the radio, sample during an antinode, then decode fragments."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e9e7be96",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%manim -qm CourierGameLoop\n",
    "from manim import *\n",
    "\n",
    "class CourierGameLoop(Scene):\n",
    "    def construct(self):\n",
    "        title = Text(\"Antinode Courier Loop\", font_size=38).to_edge(UP)\n",
    "        self.play(Write(title))\n",
    "\n",
    "        labels = [\"SCAN\", \"TUNE\", \"SAMPLE\", \"DECODE\"]\n",
    "        boxes = VGroup()\n",
    "        for i, lab in enumerate(labels):\n",
    "            box = RoundedRectangle(width=2.2, height=1.0, corner_radius=0.18)\n",
    "            box.move_to(LEFT*4.2 + RIGHT*i*2.8)\n",
    "            text = Text(lab, font_size=26).move_to(box.get_center())\n",
    "            boxes.add(VGroup(box, text))\n",
    "\n",
    "        self.play(LaggedStart(*[Create(b[0]) for b in boxes], lag_ratio=0.15))\n",
    "        self.play(LaggedStart(*[Write(b[1]) for b in boxes], lag_ratio=0.15))\n",
    "\n",
    "        arrows = VGroup()\n",
    "        for i in range(3):\n",
    "            arrows.add(Arrow(boxes[i].get_right(), boxes[i+1].get_left(), buff=0.15))\n",
    "        loop_arrow = CurvedArrow(boxes[-1].get_bottom(), boxes[0].get_bottom(), angle=-TAU/4)\n",
    "        self.play(Create(arrows), Create(loop_arrow))\n",
    "\n",
    "        hints = VGroup(\n",
    "            Text(\"RF bins\", font_size=20).next_to(boxes[0], DOWN),\n",
    "            Text(\"CH / RATE / PWR / FILT\", font_size=20).next_to(boxes[1], DOWN),\n",
    "            Text(\"FIRE at ANTI\", font_size=20).next_to(boxes[2], DOWN),\n",
    "            Text(\"fragments\", font_size=20).next_to(boxes[3], DOWN),\n",
    "        )\n",
    "        self.play(LaggedStart(*[Write(h) for h in hints], lag_ratio=0.15))\n",
    "\n",
    "        token = Dot(boxes[0].get_center() + UP*0.75)\n",
    "        self.play(FadeIn(token))\n",
    "        for i in range(1, 4):\n",
    "            self.play(token.animate.move_to(boxes[i].get_center() + UP*0.75), run_time=0.6)\n",
    "        self.play(token.animate.move_to(boxes[0].get_center() + UP*0.75), run_time=0.8)\n",
    "        self.wait(1)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dfff0398",
   "metadata": {},
   "source": [
    "## 12. Manim Scene 3 — Antinode timing meter\n",
    "\n",
    "This scene is useful for explaining why the player should not fire randomly. The best time to sample is when the wave meter is near an antinode."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a7f40032",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%manim -qm AntinodeTimingMeter\n",
    "from manim import *\n",
    "import numpy as np\n",
    "\n",
    "class AntinodeTimingMeter(Scene):\n",
    "    def construct(self):\n",
    "        title = Text(\"Timing Skill: FIRE at ANTI, avoid NULL\", font_size=34).to_edge(UP)\n",
    "        self.play(Write(title))\n",
    "\n",
    "        axes = Axes(x_range=[0, 2*np.pi, np.pi/2], y_range=[-1.2, 1.2, 0.5], x_length=9, y_length=3)\n",
    "        curve = axes.plot(lambda x: np.cos(x), x_range=[0, 2*np.pi])\n",
    "        self.play(Create(axes), Create(curve))\n",
    "\n",
    "        anti_text = Text(\"ANTI: high capture chance\", font_size=24).next_to(axes, UP).shift(DOWN*0.15)\n",
    "        null_text = Text(\"NULL: fade / miss\", font_size=24).next_to(axes, DOWN)\n",
    "        self.play(Write(anti_text), Write(null_text))\n",
    "\n",
    "        dot = Dot(axes.c2p(0, 1))\n",
    "        fire = Text(\"FIRE\", font_size=26).next_to(dot, UP)\n",
    "        self.play(FadeIn(dot), Write(fire))\n",
    "\n",
    "        path_points = [axes.c2p(x, np.cos(x)) for x in np.linspace(0, 2*np.pi, 80)]\n",
    "        path = VMobject().set_points_smoothly(path_points)\n",
    "        self.play(MoveAlongPath(dot, path), run_time=4, rate_func=linear)\n",
    "        self.wait(1)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f468d442",
   "metadata": {},
   "source": [
    "## 13. Manim Scene 4 — Fourier filter choice\n",
    "\n",
    "This animation shows the game meaning of filter selection:\n",
    "\n",
    "- `FAST`: wide, responsive, catches hopping but admits noise\n",
    "- `MED`: balanced\n",
    "- `SLOW`: narrow/smooth, better under noise"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "718041b1",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%manim -qm FourierFilterChoice\n",
    "from manim import *\n",
    "\n",
    "class FourierFilterChoice(Scene):\n",
    "    def construct(self):\n",
    "        title = Text(\"Fourier Skill: Choose the Right Filter\", font_size=34).to_edge(UP)\n",
    "        self.play(Write(title))\n",
    "\n",
    "        axes = Axes(x_range=[0, 10, 1], y_range=[0, 4, 1], x_length=8, y_length=3).shift(UP*0.2)\n",
    "        self.play(Create(axes))\n",
    "\n",
    "        peaks = VGroup()\n",
    "        peak_data = [(2, 1.3, \"noise\"), (4.8, 3.4, \"courier\"), (6.1, 2.3, \"ghost\"), (8.4, 1.2, \"noise\")]\n",
    "        for x, h, lab in peak_data:\n",
    "            line = Line(axes.c2p(x, 0), axes.c2p(x, h), stroke_width=6)\n",
    "            text = Text(lab, font_size=18).next_to(line, UP)\n",
    "            peaks.add(VGroup(line, text))\n",
    "        self.play(LaggedStart(*[Create(p[0]) for p in peaks], lag_ratio=0.1))\n",
    "        self.play(LaggedStart(*[Write(p[1]) for p in peaks], lag_ratio=0.1))\n",
    "\n",
    "        fast = Rectangle(width=4.0, height=2.8).move_to(axes.c2p(5.2, 1.4))\n",
    "        med = Rectangle(width=2.4, height=2.8).move_to(axes.c2p(5.0, 1.4))\n",
    "        slow = Rectangle(width=1.2, height=2.8).move_to(axes.c2p(4.8, 1.4))\n",
    "\n",
    "        label = Text(\"FAST: wide, tracks hopping\", font_size=24).to_edge(DOWN)\n",
    "        self.play(Create(fast), Write(label))\n",
    "        self.wait(0.8)\n",
    "        self.play(ReplacementTransform(fast, med), Transform(label, Text(\"MED: balanced\", font_size=24).to_edge(DOWN)))\n",
    "        self.wait(0.8)\n",
    "        self.play(ReplacementTransform(med, slow), Transform(label, Text(\"SLOW: stable in noisy air\", font_size=24).to_edge(DOWN)))\n",
    "        self.wait(1)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ec23fb22",
   "metadata": {},
   "source": [
    "## 14. Manim Scene 5 — Laplace smoothing / lock meter\n",
    "\n",
    "This shows why `FAST` and `SLOW` feel different. A fast lock reacts quickly but jitters. A slow lock is stable but delayed."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d89b5641",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%manim -qm LaplaceLockMeter\n",
    "from manim import *\n",
    "import numpy as np\n",
    "\n",
    "class LaplaceLockMeter(Scene):\n",
    "    def construct(self):\n",
    "        title = Text(\"Laplace Idea: Fast vs Slow Lock Response\", font_size=32).to_edge(UP)\n",
    "        self.play(Write(title))\n",
    "\n",
    "        axes = Axes(x_range=[0, 6, 1], y_range=[0, 1.2, 0.2], x_length=8, y_length=3).shift(UP*0.1)\n",
    "        self.play(Create(axes))\n",
    "\n",
    "        fast = axes.plot(lambda t: 1 - np.exp(-t/0.45), x_range=[0, 6])\n",
    "        slow = axes.plot(lambda t: 1 - np.exp(-t/1.8), x_range=[0, 6])\n",
    "        fast_label = Text(\"FAST\", font_size=24).next_to(axes.c2p(2, 0.98), UP)\n",
    "        slow_label = Text(\"SLOW\", font_size=24).next_to(axes.c2p(4, 0.86), DOWN)\n",
    "\n",
    "        eq = MathTex(r\"H(s)=\\frac{1}{\\tau s+1}\").scale(0.85).to_edge(DOWN)\n",
    "        self.play(Create(fast), Write(fast_label))\n",
    "        self.play(Create(slow), Write(slow_label))\n",
    "        self.play(Write(eq))\n",
    "        self.wait(2)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "446725d2",
   "metadata": {},
   "source": [
    "## 15. Suggested OLED teaching screens\n",
    "\n",
    "These are not firmware changes in this notebook. They are presentation ideas for explaining or future tuning.\n",
    "\n",
    "### Best immediate teaching phrase\n",
    "\n",
    "```text\n",
    "WAIT ANTI\n",
    "AVOID NULL\n",
    "```\n",
    "\n",
    "### Strong failure report idea\n",
    "\n",
    "```text\n",
    "MISS: NULL\n",
    "WAIT ANTI\n",
    "USE MED FILT\n",
    "```\n",
    "\n",
    "### Best level briefing style\n",
    "\n",
    "```text\n",
    "L5 HOPPING\n",
    "USE FAST\n",
    "FIRE AT ANTI\n",
    "```\n",
    "\n",
    "These messages make the game easier to learn because the player gets a direct **cause → action** explanation."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eaaa58d2",
   "metadata": {},
   "source": [
    "## 16. Summary: why this game is now strong\n",
    "\n",
    "The Courier game is fun and educational because it combines:\n",
    "\n",
    "- **search**: scan the RF lanes\n",
    "- **deduction**: real signal vs ghost/multipath\n",
    "- **timing**: wait for an antinode\n",
    "- **tuning**: match channel/rate/power\n",
    "- **filter choice**: FAST/MED/SLOW based on the level\n",
    "- **risk management**: battery and trace\n",
    "\n",
    "The most important sentence for teaching the game is:\n",
    "\n",
    "> Strong RF is not always good RF. The player must find the real signal and sample it when the wave field is constructive.\n",
    "\n",
    "That is what turns Black Box Courier into **Antinode Courier**."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "pygments_lexer": "ipython3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
